namespace: model-serving
lens_app:
  image:
    repository: anhtu293/lens-app
    tag: "0.0.1"
    pullPolicy: Always
  port: 8000

ocr_app:
  image:
    repository: anhtu293/ocr-app
    tag: "0.0.1"
    pullPolicy: Always

translation_app:
  image:
    repository: anhtu293/translation-app
    tag: "0.0.1"
    pullPolicy: Always

rabbitmq:
  host: 10.97.156.180
  user: rabbitmq
  # password: rabbitmq
