.PHONY: all logging-cluster metrics-cluster model-serving-cluster

all: logging-cluster metrics-cluster model-serving-cluster

logging-cluster:
	./deploy.sh logging-cluster

metrics-cluster:
	./deploy.sh metrics-cluster

model-serving-cluster:
	./deploy.sh model-serving-cluster
