apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - port: {{ .Values.grafana.service.servicePort }}
      targetPort: {{ .Values.grafana.service.containerPort }}
  selector:
    app: grafana
  type: ClusterIP
