namespace: monitoring
prometheus:
  service:
    port: 9090
    host: localhost
nodeExporter:
  service:
    host: node-exporter
    port: 9100
cadvisor:
  service:
    host: 10.99.150.72
    port: 8080
lensApp:
  service:
    host: otel-lens-metrics
    port: 8080
