namespace: model-serving
lens_app:
  image:
    repository: anhtu293/lens-app
    tag: "0.0.1"
    pullPolicy: Always
  port: 8000
  metric_service_name: lens-service
  metric_service_version: "0.0.1"

ocr_app:
  image:
    repository: anhtu293/ocr-app
    tag: "0.0.1"
    pullPolicy: Always
  metric_service_name: ocr-service
  metric_service_version: "0.0.1"

translation_app:
  image:
    repository: anhtu293/translation-app
    tag: "0.0.1"
    pullPolicy: Always
  metric_service_name: translation-service
  metric_service_version: "0.0.1"

rabbitmq:
  host: 10.103.235.85
  user: rabbitmq
  # password: rabbitmq

jaeger:
  agent_host: 192.168.49.2
  agent_port: "30522"
