namespace: model-serving
lens_app:
  image:
    repository: anhtu293/lens-app
    tag: "latest"
    pullPolicy: Always
  port: 8000
  metric_service_name: lens-service
  metric_service_version: "0.0.1"
  metric_port: 8099

ocr_app:
  image:
    repository: anhtu293/ocr-app
    tag: "latest"
    pullPolicy: Always
  metric_service_name: ocr-service
  metric_service_version: "0.0.1"

translation_app:
  image:
    repository: anhtu293/translation-app
    tag: "latest"
    pullPolicy: Always
  metric_service_name: translation-service
  metric_service_version: "0.0.1"

rabbitmq:
  host: rabbitmq
  user: rabbitmq

jaeger:
  agent_host: jaeger-agent
  agent_port: "6831"
