apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: jaeger-port
      protocol: UDP
      name: jaeger-port
    - port: {{ .Values.service.uiPort }}
      targetPort: ui-port
      protocol: TCP
      name: ui-port
