apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  annotations:
    # for the NGINX's nginx-ingress
    nginx.org/proxy-connect-timeout: 3600s
    nginx.org/proxy-read-timeout: 3600s
    nginx.org/proxy-send-timeout: 3600s
    # for the default ingress-nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: lens.example.com
      http:
        paths:
        - path: /translate
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-lens-app
              port:
                number: 8000
        - path: /docs
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-lens-app
              port:
                number: 8000
        - path: /openapi.json
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-lens-app
              port:
                number: 8000
        - path: /healthcheck
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-lens-app
              port:
                number: 8000
