apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: prometheus-port
  selector:
    app: prometheus
  type: ClusterIP
