apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 55000
      targetPort: https
  selector:
    name: cadvisor
