apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - alert-rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - "alertmanager:9093"

    scrape_configs:
      - job_name: 'node'
        scrape_interval: 5s
        static_configs:
          - targets: [{{ .Values.nodeExporter.service.host }}:{{ .Values.nodeExporter.service.port }}]

      - job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
          - targets: [{{ .Values.cadvisor.service.host }}:{{ .Values.cadvisor.service.port }}]

      - job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
          - targets: [{{ .Values.prometheus.service.host }}:{{ .Values.prometheus.service.port }}]

      - job_name: 'otel-lens-metrics'
        scrape_interval: 10s
        static_configs:
          - targets: [{{ .Values.lensApp.service.host }}:{{ .Values.lensApp.service.port }}]
